AWSTemplateFormatVersion: 2010-09-09
Description: |
  CloudFormation Template for Roman Numerals Converter Application.
  This template creates Python Flask Web Application on Amazon Linux 2023
  EC2 Instance with custom security group allowing http connections on port 80 and SSH connection on port 22.
  Roman Numerals Converter Application is downloaded from Github repository, then installed on Flask.
  The website converts decimal numbers to Roman numerals and provides a Roman Numerals Converter.
Parameters:
  amiid:
    Description: select image
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64'
  myec2ins:
    Description: select ec2 type
    Type: String
    Default: t2.micro
    AllowedValues:
         - t2.small
         - t2.nano
         - t2.micro
       
Resources:
  mysecGroupName:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow ssh and http
     
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
     
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: bendar
      ImageId: !Ref amiid
      InstanceType: !Ref myec2ins
     
      SecurityGroupIds:
        - !Ref mysecGroupName
      UserData: !Base64 |
        #!/bin/bash -ex
        dnf update -y
        dnf install python3 -y
        dnf install python3-pip -y
        pip3 install flask
        dnf install git -y
        FOLDER="https://raw.githubusercontent.com/SimretTesfu/Aws-projects/main/clarusway-aws-devops-DE-09/AWS/projects/Project-001-roman-numerals-converter/templates"
        cd /home/ec2-user
        wget -P templates ${FOLDER}/index.html
        wget -P templates ${FOLDER}/result.html
        wget https://raw.githubusercontent.com/SimretTesfu/Aws-projects/main/clarusway-aws-devops-DE-09/AWS/projects/Project-001-roman-numerals-converter/app.py
        python3 app.py
      Tags:
        - Key: Name
          Value: !Sub websever of ${AWS::StackName}
  
Outputs:
  weburl:
    Value: !Sub http://${myEC2Instance.PublicIp}
    