AWSTemplateFormatVersion: 2010-09-09
Description: |
  CloudFormation Template for Roman Numerals Converter Application.
  This template creates Python Flask Web Application on Amazon Linux 2023
  EC2 Instance with custom security group allowing http connections on port 80 and SSH connection on port 22.
  Roman Numerals Converter Application is downloaded from Github repository, then installed on Flask.
  The website converts decimal numbers to Roman numerals and provides a Roman Numerals Converter.
  
Parameters:
  myimage:
    Description: enter your image
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64'
  mykeyname:
    Description: enter your keypar
    Type: AWS::EC2::KeyPair::KeyName
    Default: bendar
  myinstance:
    Description: select instance
    Type: String
    Default: t2.micro
    AllowedValues:
         - t2.micro
         - t2.nano
         - t2.small
  
Resources:
  mysecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow http and ssh
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref mykeyname
      ImageId: !Ref myimage
      InstanceType: !Ref myinstance 
      SecurityGroupIds:
        - !Ref mysecGroup
      UserData: !Base64 |
        #!/bin/bash -ex
        dnf update -y
        dnf install python3 -y
        dnf install python3-pip -y
        pip3 install flask
        dnf install git -y
        FOLDER="https://raw.githubusercontent.com/SimretTesfu/Aws-projects/main/clarusway-aws-devops-DE-09/AWS/projects/Project-001-roman-numerals-converter/templates"
        cd /home/ec2-user
        wget -P templates ${FOLDER}/index.html
        wget -P templates ${FOLDER}/result.html
        wget https://raw.githubusercontent.com/SimretTesfu/Aws-projects/main/clarusway-aws-devops-DE-09/AWS/projects/Project-001-roman-numerals-converter/app.py
        python3 app.py
      Tags:
        - Key: Name
          Value: !Sub Dec to roman ${AWS::StackName}
 
Outputs:
  weburl: 
    Value: !Sub 
      - http://${address}
      - address: !GetAtt  myEC2Instance.PublicIp
